language: php

php:
  - 5.6
  - hhvm

before_script:
  ## Composer
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - php vendor/bin/smartdata data:update
  - phpunit

matrix:
  allow_failures:
    - php: hhvm
